version: "3"

services:
  web:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py loaddata fixtures/character.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
