# Generated by Django 3.0 on 2019-12-07 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('number_of_pieces', models.IntegerField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Board')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side1_turn', models.BooleanField(default=True)),
                ('side2_turn', models.BooleanField(default=False)),
                ('side1_mask', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('side2_mask', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.Game')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='character1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='character1', to='game.Character'),
        ),
        migrations.AddField(
            model_name='board',
            name='character2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='character2', to='game.Character'),
        ),
    ]
